/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Controllers.ViewUpcomingGames;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Colum
 */
public class ViewUpcomingGameUI extends javax.swing.JFrame {

    boolean logged = false;
    /**
     * 
     * Creates new form ViewUpcomingGame
     */
    String username;
    DefaultListModel demoList = new DefaultListModel();
    public ViewUpcomingGameUI(String username) {
        logged = true;
        this.username=username;
        ViewUpcomingGames temp = new ViewUpcomingGames();
        ArrayList<String[]> fList = temp.getFixture();
        String lie;
        for(int i = 0; i < fList.size(); i++){
            lie= (fList.get(i)[0]+ "vs" +fList.get(i)[1]+ "on the" +fList.get(i)[2]);
             demoList.addElement(lie);
        }
        jList=new JList(demoList);
        initComponents();
    }

    ViewUpcomingGameUI() {
        ViewUpcomingGames temp = new ViewUpcomingGames();
        ArrayList<String[]> fList = temp.getFixture();
        String lie;
        for(int i = 0; i < fList.size(); i++){
            lie= (fList.get(i)[0]+ "vs" +fList.get(i)[1]+ "on the" +fList.get(i)[2]);
             demoList.addElement(lie);
        }
        jList=new JList(demoList);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      
        jScrollPane1.setViewportView(jList);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(logged){
            MainMenuUI temp = new MainMenuUI(username);
            temp.setVisible(true);
            dispose();
        }
        else{
            guestMenu temp = new guestMenu();
            temp.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    DefaultListModel<String> model = new DefaultListModel<>();
    private JList<String> jList = new JList<>(model);
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
